# Generated by Django 4.2.3 on 2024-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_insc'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
