# Generated by Django 4.2.3 on 2024-03-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_formation_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
